version: "3.0"
services:
  reverse-proxy:
    image: reverse-proxy
    container_name: "reverse-proxy"
    ports:
      - "80:80"
      - "443:443"
    restart:
      unless-stopped
    volumes:
      - "./letsencrypt:/etc/letsencrypt"
    environment:
      CERTBOT_AGREE: ""
